name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔐 Replace secrets in your HTML before deployment
      - name: Replace API keys in HTML
        run: |
          sed -i 's|__APP_INSIGHTS_CONNECTION_STRING__|${{ secrets.APP_INSIGHTS_CONNECTION_STRING }}|g' webapp.html
          sed -i 's|__SUBMIT_POST_URL__|${{ secrets.SUBMIT_POST_URL }}|g' webapp.html
          sed -i 's|__REWRITE_TEXT_URL__|${{ secrets.REWRITE_TEXT_URL }}|g' webapp.html
          sed -i 's|__GET_EVENTS_URL__|${{ secrets.GET_EVENTS_URL }}|g' webapp.html

      # 🚀 Deploy to Azure Static Web Apps
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"       # Your HTML files are in root folder
          api_location: ""        # No API folder
          output_location: ""     # No build output folder

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job

    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
